
application:
  security:
    jwt:
      secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refreshToken:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pong
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
